version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.4
  workflows:
    example-workflow:
      jobs:
        - cypress/run:
            install-browsers: true 
            parallelism: 9 
            include-branch-in-node-cache-key: false 
            package-manager: npm 
            cypress-command: yarn smoke split0true 
